# Generated by Django 5.2.3 on 2025-06-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
