# Generated by Django 5.2.3 on 2025-06-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_registro_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoProvincial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(choices=[(1, 'PRESIDENTE PROVINCIAL'), (2, 'COORDINADOR OPERATIVO Y DE ORGANIZACIÓN'), (3, 'COORDINADOR DE TECNOLOGIA Y REDES'), (4, 'COORDINADORA DE LA MUJER'), (5, 'COORDINADOR DE LA JUVENTUD'), (6, 'COORDINADOR DE SECTORES PRODUCTIVOS'), (7, 'COORDINADOR DE DEPORTES'), (8, 'COORDINADOR DE IGLESIAS Y ORGANIZACIONES SIN FINES DE LUCRO'), (9, 'COORDINADOR DE TRANSPORTE'), (10, 'COORDINADOR SECTOR SALUD'), (11, 'COORDINADOR DE PROFESIONALES INDEPENDIENTES'), (12, 'COORDINADOR DE ASUNTOS COMUNITARIOS')], unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('oficio', models.CharField(max_length=100)),
            ],
        ),
    ]
