# Generated by Django 5.2.3 on 2025-06-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_cargoprovincial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoprovincial',
            name='provincia',
            field=models.CharField(choices=[('Azua', 'Azua'), ('Bahoruco', 'Bahoruco'), ('Barahona', 'Barahona'), ('Dajabón', 'Dajabón'), ('Distrito Nacional', 'Distrito Nacional'), ('Duarte', 'Duarte'), ('Elías Piña', 'Elías Piña'), ('El Seibo', 'El Seibo'), ('Espaillat', 'Espaillat'), ('Hato Mayor', 'Hato Mayor'), ('Hermanas Mirabal', 'Hermanas Mirabal'), ('Independencia', 'Independencia'), ('La Altagracia', 'La Altagracia'), ('La Romana', 'La Romana'), ('La Vega', 'La Vega'), ('María Trinidad Sánchez', 'María Trinidad Sánchez'), ('Monseñor Nouel', 'Monseñor Nouel'), ('Monte Cristi', 'Monte Cristi'), ('Monte Plata', 'Monte Plata'), ('Pedernales', 'Pedernales'), ('Peravia', 'Peravia'), ('Puerto Plata', 'Puerto Plata'), ('Samaná', 'Samaná'), ('Sánchez Ramírez', 'Sánchez Ramírez'), ('San Cristóbal', 'San Cristóbal'), ('San José de Ocoa', 'San José de Ocoa'), ('San Juan', 'San Juan'), ('San Pedro de Macorís', 'San Pedro de Macorís'), ('Santiago', 'Santiago'), ('Santiago Rodríguez', 'Santiago Rodríguez'), ('Santo Domingo', 'Santo Domingo'), ('Valverde', 'Valverde')], default=str, max_length=50),
            preserve_default=False,
        ),
    ]
