# Generated by Django 5.2.3 on 2025-06-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_miembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('Azua', 'Azua'), ('Bahoruco', 'Bahoruco'), ('Barahona', 'Barahona'), ('Dajabón', 'Dajabón'), ('Distrito Nacional', 'Distrito Nacional'), ('Duarte', 'Duarte'), ('Elías Piña', 'Elías Piña'), ('El Seibo', 'El Seibo'), ('Espaillat', 'Espaillat'), ('Hato Mayor', 'Hato Mayor'), ('Hermanas Mirabal', 'Hermanas Mirabal'), ('Independencia', 'Independencia'), ('La Altagracia', 'La Altagracia'), ('La Romana', 'La Romana'), ('La Vega', 'La Vega'), ('María Trinidad Sánchez', 'María Trinidad Sánchez'), ('Monseñor Nouel', 'Monseñor Nouel'), ('Monte Cristi', 'Monte Cristi'), ('Monte Plata', 'Monte Plata'), ('Pedernales', 'Pedernales'), ('Peravia', 'Peravia'), ('Puerto Plata', 'Puerto Plata'), ('Samaná', 'Samaná'), ('Sánchez Ramírez', 'Sánchez Ramírez'), ('San Cristóbal', 'San Cristóbal'), ('San José de Ocoa', 'San José de Ocoa'), ('San Juan', 'San Juan'), ('San Pedro de Macorís', 'San Pedro de Macorís'), ('Santiago', 'Santiago'), ('Santiago Rodríguez', 'Santiago Rodríguez'), ('Santo Domingo', 'Santo Domingo'), ('Valverde', 'Valverde')], max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(choices=[(1, 'PRESIDENTE MUNICIPAL'), (2, 'COORDINADOR OPERATIVO Y DE ORGANIZACIÓN'), (3, 'COORDINADOR DE TECNOLOGIA Y REDES'), (4, 'COORDINADORA DE LA MUJER'), (5, 'COORDINADOR DE LA JUVENTUD'), (6, 'COORDINADOR DE SECTORES PRODUCTIVOS'), (7, 'COORDINADOR DE DEPORTES'), (8, 'COORDINADOR DE IGLESIAS Y ORGANIZACIONES SIN FINES DE LUCRO'), (9, 'COORDINADOR DE TRANSPORTE'), (10, 'COORDINADOR SECTOR SALUD'), (11, 'COORDINADOR DE PROFESIONALES INDEPENDIENTES'), (12, 'COORDINADOR DE ASUNTOS COMUNITARIOS')])),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('oficio', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
