# Generated by Django 5.2.3 on 2025-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_cargomunicipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(choices=[(1, 'Presidente(a)'), (2, 'Vicepresidente(a)'), (3, 'Secretario(a) de Finanzas'), (4, 'Coordinador(a) Operativo(a)'), (5, 'Coordinador(a) Nacional de la Juventud'), (6, 'Coordinador(a) Nacional de Cultos y Organizaciones sin fines de Lucro'), (7, 'Coordinadora Nacional de La Mujer'), (8, 'Coordinador(a) Regional Santo Domingo y Distrito Nacional'), (9, 'Coordinador(a) Regional Región Norte'), (10, 'Coordinador(a) Regional Región Sur'), (11, 'Coordinador(a) Regional Región Este')], unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('oficio', models.CharField(max_length=100)),
            ],
        ),
    ]
