# Generated by Django 5.2.3 on 2025-06-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_cargomunicipal_creado_por_cargonacional_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoprovincial',
            name='orden',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PRESIDENTE PROVINCIAL'), (2, 'COORDINADOR OPERATIVO Y DE ORGANIZACIÓN'), (3, 'COORDINADOR DE TECNOLOGIA Y REDES'), (4, 'COORDINADORA DE LA MUJER'), (5, 'COORDINADOR DE LA JUVENTUD'), (6, 'COORDINADOR DE SECTORES PRODUCTIVOS'), (7, 'COORDINADOR DE DEPORTES'), (8, 'COORDINADOR DE IGLESIAS Y ORGANIZACIONES SIN FINES DE LUCRO'), (9, 'COORDINADOR DE TRANSPORTE'), (10, 'COORDINADOR SECTOR SALUD'), (11, 'COORDINADOR DE PROFESIONALES INDEPENDIENTES'), (12, 'COORDINADOR DE ASUNTOS COMUNITARIOS')]),
        ),
    ]
