# Generated by Django 5.2.3 on 2025-06-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_alter_cargoprovincial_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoprovincial',
            name='orden',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PRESIDENTE PROVINCIAL'), (2, 'COORDINADOR OPERATIVO Y DE ORGANIZACIÓN'), (3, 'COORDINADOR DE TECNOLOGIA Y REDES'), (4, 'COORDINADOR MEDICOS GENERALES Y ESPECIALISTAS'), (5, 'COORDINADOR (A) DE ENFERMERIA'), (6, 'COORDINADOR (A) DE SALUD MENTAL'), (7, 'COORDINADOR (A) DE ODONTOLOGIA'), (8, 'COORDINADOR (A) DE TECNICOS DEL SECTOR SALUD'), (9, 'COORDINADOR (A) DE BIOANALISIS'), (10, 'COORDINADOR DE IGLESIAS Y ORGANIZACIONES SIN FINES DE LUCRO'), (11, 'COORDINADOR DE PROFESIONALES INDEPENDIENTES'), (12, 'COORDINADOR DE ASUNTOS COMUNITARIOS')]),
        ),
    ]
